version: "3"

services:
  redis:
    container_name: chat_redis
    image: redis:5.0
    ports:
      - 6379:6379
  back:
    container_name: chat_back
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "8083:8083"
    volumes:
      - ./:/app/
    env_file:
      - .env