version: "3"

services:
  back:
    container_name: chat_back
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "8083:8083"
    volumes:
      - ./:/app/
    env_file:
      - .env